-- Static variables
MINIMUM_TREE_SIZE = .6
MAXIMUM_TREE_SIZE = 1.6
QUADCOEF_TREE_HP = 300
LINEARCOEF_TREE_HP = -210
CONSTANT_TREE_HP = 68
LEASH_RADIUS = 300
STARTING_LOCATION = Location(4000, -2500)
STARTING_LOCATION_DOG = Location(4000, -2600)
FOREST_ANGER_GROWTH = 3
FOREST_HATRED_GROWTH = .1
DOG_MAX_RADIUS = 500

-- Variables used by code
TREE_SHADOW_PAIRS = {}
TREES_BEING_HARVESTED = {}
PLAYER_SKELETONS = {}
PLAYER_DOGS = {}
ALL_UNITS = {}
FOREST_ANGER = 0
FOREST_HATRED = 0